#DataSource Config
spring:
  redis:
    host: 192.168.10.104
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 0
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogvue?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
  mvc:
    # 允许访问static文件目录
    static-path-pattern: /**     # /static/** 404


server:
  port: 8868
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rz.entity

logging:
  level:
   com.rz: debug

encrypt:
  body:
    aes-key: 1234567887654321 #AES加密秘钥
    des-key: 12345678 #DES加密秘钥
